/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package bestguiever;

import boardgamerental.CustomerManagerImpl;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sql.DataSource;

/**
 *
 * @author Goolomb
 */
public class openingTable extends javax.swing.JFrame {

    /**
     * Creates new form openingTable
     */
    public openingTable() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonShowLendings = new javax.swing.JButton();
        jButtonFindBoardGame = new javax.swing.JButton();
        jLabelBoardGameRental = new javax.swing.JLabel();
        jButtonAddCustomer = new javax.swing.JButton();
        jButtonAddBoardGame = new javax.swing.JButton();
        jButtonBorrow = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("bestguiever/Bundle"); // NOI18N
        jButtonShowLendings.setText(bundle.getString("BoardGameRental.jButtonShowLendings")); // NOI18N
        jButtonShowLendings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShowLendingsActionPerformed(evt);
            }
        });

        jButtonFindBoardGame.setText(bundle.getString("BoardGameRental.jButtonFindBoardGame")); // NOI18N
        jButtonFindBoardGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFindBoardGameActionPerformed(evt);
            }
        });

        jLabelBoardGameRental.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelBoardGameRental.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBoardGameRental.setText(bundle.getString("BoardGameRental.jLabelBoardGameRental")); // NOI18N

        jButtonAddCustomer.setText(bundle.getString("BoardGameRental.jButtonAddCustomer")); // NOI18N
        jButtonAddCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddCustomerActionPerformed(evt);
            }
        });

        jButtonAddBoardGame.setText(bundle.getString("BoardGameRental.jButtonAddBoardGame")); // NOI18N
        jButtonAddBoardGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddBoardGameActionPerformed(evt);
            }
        });

        jButtonBorrow.setText(bundle.getString("BoardGameRental.jButtonBorrow")); // NOI18N
        jButtonBorrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonAddCustomer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAddBoardGame))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jButtonBorrow)
                            .addComponent(jButtonShowLendings)
                            .addComponent(jButtonFindBoardGame))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabelBoardGameRental, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                .addGap(54, 54, 54))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonBorrow, jButtonFindBoardGame, jButtonShowLendings});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabelBoardGameRental, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(33, 33, 33)
                .addComponent(jButtonBorrow)
                .addGap(18, 18, 18)
                .addComponent(jButtonShowLendings)
                .addGap(18, 18, 18)
                .addComponent(jButtonFindBoardGame)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddCustomer)
                    .addComponent(jButtonAddBoardGame))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonShowLendingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShowLendingsActionPerformed
        new ShowLendingsForCustomer().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonShowLendingsActionPerformed

    private void jButtonAddCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddCustomerActionPerformed
        new AddCustomer().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonAddCustomerActionPerformed

    private void jButtonFindBoardGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFindBoardGameActionPerformed
        new FindBoardGame().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonFindBoardGameActionPerformed

    private void jButtonAddBoardGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddBoardGameActionPerformed
        new AddBoardGame().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonAddBoardGameActionPerformed

    private void jButtonBorrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrowActionPerformed
        dispose();
        new Borrow().setVisible(true);
    }//GEN-LAST:event_jButtonBorrowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(openingTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(openingTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(openingTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(openingTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new openingTable().setVisible(true);
            }
        });
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddBoardGame;
    private javax.swing.JButton jButtonAddCustomer;
    private javax.swing.JButton jButtonBorrow;
    private javax.swing.JButton jButtonFindBoardGame;
    private javax.swing.JButton jButtonShowLendings;
    private javax.swing.JLabel jLabelBoardGameRental;
    // End of variables declaration//GEN-END:variables
}
