/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package bestguiever;

/**
 *
 * @author Goolomb
 */
public class openingTable extends javax.swing.JFrame {

    /**
     * Creates new form openingTable
     */
    public openingTable() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonListAllBoardGames = new javax.swing.JButton();
        jButtonShowLendings = new javax.swing.JButton();
        jButtonFindBoardGame = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonAddCustomer = new javax.swing.JButton();
        jButtonAddBoardGame = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonListAllBoardGames.setText("List all board games");
        jButtonListAllBoardGames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListAllBoardGamesActionPerformed(evt);
            }
        });

        jButtonShowLendings.setText("Show lendings for Customer");
        jButtonShowLendings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShowLendingsActionPerformed(evt);
            }
        });

        jButtonFindBoardGame.setText("Find board game");
        jButtonFindBoardGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFindBoardGameActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Board game Rental");

        jButtonAddCustomer.setText("Add Customer");
        jButtonAddCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddCustomerActionPerformed(evt);
            }
        });

        jButtonAddBoardGame.setText("Add board game");
        jButtonAddBoardGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddBoardGameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonAddCustomer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAddBoardGame))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addComponent(jButtonFindBoardGame))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addComponent(jButtonShowLendings))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addComponent(jButtonListAllBoardGames)))
                        .addGap(0, 90, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonFindBoardGame, jButtonListAllBoardGames, jButtonShowLendings});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonListAllBoardGames)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonShowLendings)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonFindBoardGame)
                        .addGap(108, 108, 108))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonAddCustomer)
                            .addComponent(jButtonAddBoardGame))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonListAllBoardGamesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListAllBoardGamesActionPerformed
        new ListBoardGames().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonListAllBoardGamesActionPerformed

    private void jButtonShowLendingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShowLendingsActionPerformed
        new ShowMyLendings().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonShowLendingsActionPerformed

    private void jButtonAddCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddCustomerActionPerformed
        new AddCustomer().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonAddCustomerActionPerformed

    private void jButtonFindBoardGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFindBoardGameActionPerformed
        new FindBoardGame().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonFindBoardGameActionPerformed

    private void jButtonAddBoardGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddBoardGameActionPerformed
        new AddBoardGame().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonAddBoardGameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(openingTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(openingTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(openingTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(openingTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new openingTable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddBoardGame;
    private javax.swing.JButton jButtonAddCustomer;
    private javax.swing.JButton jButtonFindBoardGame;
    private javax.swing.JButton jButtonListAllBoardGames;
    private javax.swing.JButton jButtonShowLendings;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
